DROP DATABASE  IF EXISTS `pm` ;
CREATE DATABASE  IF NOT EXISTS `pm` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `pm`;
CREATE USER IF NOT EXISTS 'pm'@'%' IDENTIFIED BY '8iNbR7HgaxJGlJnq';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'pm'@'%'
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;